apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      terminationGracePeriodSeconds: 60

      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          imagePullPolicy: Always

          securityContext:
            privileged: true

          env:
            - name: TZ
              value: Europe/Amsterdam

          volumeMounts:
            - name: config
              mountPath: /config

            - name: localtime
              mountPath: /etc/localtime
              readOnly: true

            - name: dbus
              mountPath: /run/dbus
              readOnly: true

      volumes:
        - name: config
          hostPath:
            path: /home/shigarus/.home-assistant/cfg
            type: Directory

        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File

        - name: dbus
          hostPath:
            path: /run/dbus
            type: Directory
