#!/usr/bin/env bash

# To get the names of all the running applications
# yabai -m query --windows | jq -r '.[].app'

# Load all the variables I need from the yabai_env.sh file
source "$HOME/.config/yabai/yabai_env.sh"

# THIS IS NOT FOR APP I USE
# In order to prevent simple-bar freezing upon yabai restart, you'll need to add
# this line at the start of your .yabairc file
# https://www.jeantinland.com/toolbox/simple-bar/documentation/installation/#update-your-yabai-config
# osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

###############################################################################
#                              Excluded apps
###############################################################################

yabai -m rule --add app="^${apps_mgoff_normal}$" manage=off
yabai -m rule --add app="^${apps_mgoff_below}$" manage=off sub-layer=below
yabai -m rule --add app="^${apps_mgoff_above}$" manage=off sub-layer=above

###############################################################################
#                          Custom padding settings
###############################################################################

if command -v sketchybar &>/dev/null; then
    if [[ "$(system_profiler SPDisplaysDataType | grep Resolution)" == *"2160"* ]]; then
        yabai -m config top_padding 38
        yabai -m config right_padding 260
    else
        yabai -m config top_padding 10
        yabai -m config right_padding 230
    fi
    yabai -m config bottom_padding 0
    yabai -m config left_padding 0
  # Check the display size (e.g., grab the resolution here)
  # display_resolution=$(system_profiler SPDisplaysDataType | grep Resolution)
  # # First condition is to match my macbook pro, the * are used as wildcards
  # if [[ "$display_resolution" == *"3456 x 2234"* ]]; then
  #   # yabai -m config top_padding 12
  #   yabai -m config top_padding 12
  #   yabai -m config bottom_padding 0
  #   yabai -m config left_padding 0
  #   yabai -m config right_padding 230
  #   # Resolution for my shorts
  # elif [[ "$display_resolution" == *"1536 x 2048"* ]]; then
  #   yabai -m config top_padding 38
  #   yabai -m config bottom_padding 220
  #   yabai -m config left_padding 0
  #   yabai -m config right_padding 0
  # elif [[ "$display_resolution" == *"3200 x 1800"* ]]; then
  #   # # This matches my asus 27 inch monitor
  #   # # yabai -m config top_padding 39
  #   yabai -m config top_padding 38
  #   yabai -m config bottom_padding 0
  #   yabai -m config left_padding 0
  #   yabai -m config right_padding 230
  # elif [[ "$display_resolution" == *"3024 x 1964"* ]]; then
  #   # # This matches my macbook 14 inch
  #   # # yabai -m config top_padding 39
  #   yabai -m config top_padding 10
  #   yabai -m config bottom_padding 0
  #   yabai -m config left_padding 0
  #   yabai -m config right_padding 230
  # fi
else
  yabai -m config top_padding 02
  yabai -m config bottom_padding 00
fi

###############################################################################
#                             Yabai Spaces
###############################################################################

# I want to have all the apps in desktop 2, as it is my work monitor near laptop.
# If apps are organized incorrectly, just restart yabai:
# https://github.com/koekeishiya/yabai/issues/1685

yabai -m space 2 --label default


###############################################################################
#                             sub-layer=normal
###############################################################################

# https://github.com/koekeishiya/yabai/issues/1929

# Set all apps to the "normal" sub-layer, otherwise they all start on the "below"
# sub-layer. Doing this fixed the issue with floating where their floating windows would show on top
# of other apps

yabai -m rule --add app=".*" sub-layer=normal

###############################################################################
#                                  Misc
###############################################################################

## NOT SURE IF IT IS NEEDED FOR ME.
# global settings
# When I leave youtube or chrome, hammerspoon will move the mouse to the corner
# "mouse_follows_focus on" will move the mouse back to the center, but DISABLE it or it will
# be a nightmare to use iStat Menus
yabai -m config mouse_follows_focus off

# Configure the layout mode
# "stack" - is what I use, keeps a single app on the front
# "bsp" - binary space partitioning enables automatic tiling (partitioning)
# "float" - default mode, windows are not managed
yabai -m config layout stack
# yabai -m config layout bsp
# yabai -m config layout float

yabai -m config window_shadow off

yabai -m config window_opacity on
opacity_value=0.87
yabai -m signal --add event=window_focused app="^${apps_transparent}$" action="yabai -m config active_window_opacity $opacity_value"
# I don't want to be moving Ghostty around to other desktops, so I'll set its
# opacity to 1 and manage its transparency through the ghostty config file
yabai -m signal --add event=window_focused app="Ghostty" action="yabai -m config active_window_opacity 1"
yabai -m signal --add event=window_focused app="^${apps_transparent}$" action="yabai -m config normal_window_opacity 0.00001"

# I want the apps here to always be shown, probably they'll be on the right
# padding section. This is my "sticky notes"
yabai -m rule --add app="^${apps_transp_ignore}$" opacity=$opacity_value

# When any other app gains focus, reset both active and background window opacity to fully visible
yabai -m signal --add event=window_focused app!="^${apps_transparent}$" action="yabai -m config active_window_opacity 1.0"
yabai -m signal --add event=window_focused app!="^${apps_transparent}$" action="yabai -m config normal_window_opacity 1.0"

# Nice trick shared by @timhansinger8030 in my YouTube video https://youtu.be/SLCR1oO65GI
# Allows to see mission control apps when calling mission control from a transparent app
yabai -m signal --add event=mission_control_enter action="yabai -m config normal_window_opacity 1.0"
yabai -m signal --add event=mission_control_exit action="yabai -m config active_window_opacity 1.0"

###############################################################################
#                              Signal events
###############################################################################

# Adds a signal that, when a window gains focus, triggers a custom action in SketchyBar
# (presumably to update the status bar based on the focused window).
# https://github.com/FelixKratz/dotfiles
# I'm not sure what this does, I don't see a difference
# Not sure if related to "skhd shortcuts should trigger the sketchybar event" in
# the owner dotfiles
if command -v sketchybar &>/dev/null; then
  yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
fi

###############################################################################
#                                Defaults
###############################################################################

yabai -m config \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  insert_feedback_color 0xffd75f5f \
  window_animation_duration 2 \
  window_animation_frame_rate 120 \
  window_opacity_duration 0.0 \
  active_window_border_color 0xff775759 \
  normal_window_border_color 0xff555555 \
  window_border_width 4 \
  window_border_radius 12 \
  window_border_blur off \
  window_border_hidpi on \
  window_border off \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  window_gap 06 \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

# THIS IS VERY IMPORTANT
# It ensures that when I restart yabai, all the rules (including the manage=off rules)
# are reapplied to existing windows
# Otherwise yabai takes care of management and I couldnt resize apps like
# packet tracer for example
yabai -m rule --apply
